#pragma once

#include <stdbool.h>
#include "entities.h"
#include "utilities.h"

#define SCREEN_WIDTH 1200
#define SCREEN_HEIGHT 900

#define PLAYER_WIDTH 100
#define PLAYER_HEIGHT 30
#define PLAYER_SPEED 500.0f
#define MAX_BULLETS 3
#define BULLET_RELOAD_TIME 500.f

#define NORMAL_ENNEMY_WIDTH 50
#define NORMAL_ENNEMY_HEIGHT 20
#define NORMAL_ENNEMY_SPEED 20.0f
#define NORMAL_ENNEMY_SHOOT_RATE 300
#define NORMAL_ENEMY_BOOST_INTERVAL 5000.0f
#define NORMAL_ENEMY_BOOST_FACTOR 1.1f

#define NORMAL_ENNEMY_BULLET_WIDTH 10
#define NORMAL_ENNEMY_BULLET_HEIGHT 20
#define NORMAL_ENNEMY_BULLET_SPEED 200.0f

#define FAST_ENNEMY_SPEED 50.0f

#define FAST_ENNEMY_SHOOT_RATE 200
#define FAST_ENNEMY_BULLET_SPEED 200.0f

#define BULLET_WIDTH 10
#define BULLET_HEIGHT 20
#define BULLET_SPEED 600.0f

#define HEART_SPEED 100.0f
#define HEART_RATE 8

#define LEVEL1_LINES 3
#define LEVEL1_COLUMNS 6

#define LEVEL2_LINES 3
#define LEVEL2_COLUMNS 6

#define LEVEL3_LINES 6
#define LEVEL3_COLUMNS 4

#define LEVEL4_LINES 3
#define LEVEL4_COLUMNS 8


void update(Game *game, float dt);


